package edu.brandeis.cs12b.pa4.provided;

public enum VehicleError {
	CARERROR("ERROR: CAR FAILED TO MOVE"),
	SNOWPLOWERROR("ERROR: SNOWPLOW FAILED TO MOVE"),
	LEFTSNOWPLOWERROR("ERROR: LEFTSNOWPLOW FAILED TO MOVE"),
	RIGHTSNOWPLOWERROR("ERROR: RIGHTSNOWPLOW FAILED TO MOVE"),
	HUMANCARERROR("ERROR: HUMANCAR FAILED TO MOVE"),
	
	CARPLACEMENT("ERROR: CAR FAILED TO BE PLACED"),
	SNOWPLOWPLACEMENT("ERROR: SNOWPLOW FAILED TO BE PLACED"),
	LEFTSNOWPLOWPLACEMENT("ERROR: LEFTSNOWPLOW FAILED TO PLACED"),
	RIGHTSNOWPLOWPLACEMENT("ERROR: RIGHTSNOWPLOW FAILED TO PLACED"),
	HUMANCARPLACEMENT("ERROR: HUMANCAR FAILED TO BE PLACED");
	
	
	private final String error;
	
	private VehicleError(String error){
        this.error = error;
    }
	
	public String toString(){
		return this.error;
	}
	
	
}
